-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
-keep class com.google.** { *; }
-dontwarn io.flutter.embedding.**
-keepattributes *Annotation*
-keepattributes Signature
-keepattributes Exceptions
